#!/bin/bash
# NetStrike installer
# Installs dependencies, the binary, wrapper, icon, desktop entry,
# and a sudoers rule for passwordless launch.
set -e

if [ "$(id -u)" -ne 0 ]; then
    echo "[!] Run as root: sudo ./install.sh"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Figure out which non-root user is doing this install
TARGET_USER="${SUDO_USER:-$(logname 2>/dev/null || echo '')}"
if [ -z "$TARGET_USER" ] || [ "$TARGET_USER" = "root" ]; then
    TARGET_USER="kali"
fi

BASE_PKGS="python3 python3-gi gir1.2-gtk-4.0 gir1.2-adw-1 \
aircrack-ng nmap iw sudo \
hicolor-icon-theme desktop-file-utils libgtk-4-bin"

if ! command -v apt-get >/dev/null 2>&1; then
    echo "[!] This installer assumes a Debian/Kali system with apt."
    echo "    Install manually: $BASE_PKGS"
    exit 1
fi

echo "[*] Updating package lists..."
DEBIAN_FRONTEND=noninteractive apt-get update -qq

echo "[*] Installing dependencies..."
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq $BASE_PKGS

# Verify Python GTK4/libadwaita bindings actually import
if ! python3 -c "import gi; gi.require_version('Gtk','4.0'); gi.require_version('Adw','1'); from gi.repository import Gtk, Adw" 2>/dev/null; then
    echo "[!] Python GTK4/libadwaita bindings not importable."
    echo "    Check: python3-gi, gir1.2-gtk-4.0, gir1.2-adw-1"
    exit 1
fi

echo "[*] Installing binary -> /usr/local/bin/netstrike"
install -m 755 "$SCRIPT_DIR/netstrike.py" /usr/local/bin/netstrike

echo "[*] Installing wrapper -> /usr/local/bin/netstrike-launcher"
install -m 755 "$SCRIPT_DIR/netstrike-launcher" /usr/local/bin/netstrike-launcher

echo "[*] Installing icon -> /usr/share/icons/hicolor/scalable/apps/"
install -D -m 644 "$SCRIPT_DIR/netstrike.svg" \
    /usr/share/icons/hicolor/scalable/apps/netstrike.svg

echo "[*] Installing desktop entry -> /usr/share/applications/"
install -m 644 "$SCRIPT_DIR/netstrike.desktop" \
    /usr/share/applications/netstrike.desktop

echo "[*] Installing sudoers rule for user '$TARGET_USER'"
SUDOERS_FILE="/etc/sudoers.d/netstrike"
cat > "$SUDOERS_FILE" <<EOF
# NetStrike: allow passwordless launch with preserved env
# Generated by netstrike installer
$TARGET_USER ALL=(root) NOPASSWD: SETENV: /usr/local/bin/netstrike
EOF
chmod 0440 "$SUDOERS_FILE"
if ! visudo -cf "$SUDOERS_FILE" >/dev/null 2>&1; then
    echo "[!] sudoers file failed validation — removing"
    rm -f "$SUDOERS_FILE"
    echo "    Launch manually instead: sudo -E netstrike"
else
    echo "    -> $SUDOERS_FILE validated"
fi

echo "[*] Refreshing caches..."
gtk-update-icon-cache -f /usr/share/icons/hicolor 2>/dev/null || true
update-desktop-database /usr/share/applications 2>/dev/null || true

echo
echo "[+] Installed."
echo "    Launch: tap NetStrike in the app drawer (passwordless)"
echo "    Or from terminal: netstrike-launcher"
echo "    Activity log: ~/.config/netstrike/activity.log"
echo "    Captures:     ~/Documents/netstrike/captures/"
